name: CI

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_PUSH_GH }}
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version-file: .nvmrc
          token: ${{ secrets.NPM_TOKEN }}
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PUSH_GH }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run the tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: lint-ts
        run: yarn type:check